services:
  renamer:
    image: "lemonc7/renamer:latest"
    container_name: renamer
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config:ro # 可以在config.toml修改默认设置
      - /media:/mnt/media:rw
    ports:
      - 8080:8080
    restart: always
